### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by cow1337killer3** [PolarGoose/Handle2#1]
Using --path doesn't return any results, but if I use --dump-all-handles, I can find handles for the path I previously specified

**Comment by PolarGoose** [comment]
Hello @cow1337killer3,

Thank you for submitting the issue.
Sorry for the bug. I will look into it.

Do you have any particular details? Maybe a way how to reproduce it?
In the meantime I will try it on my machine on some generic use cases.

**Comment by PolarGoose** [comment]
Tried it on my machine. It works:
```
C:\Users\username\Downloads>Handle2.exe --path "C:\Users\username\Downloads"
C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe pid: 21376 DLAPTOP/username
  C:\Users\username\Downloads\DOC-1.pdf
------------------------------------------------------------------------------
```

Could you please provide more details?
